Sprint task 1063 create manuscript table and model class
gigascience/gigadb-website pull request #1074
Opened 2022-06-30 05:57 UTC by kencho51

# Pull request for issue: #1064 

This is a pull request for the following functionalities:

* Describe functionality 1
* Describe functionality 2
* *Etc.*

## How to test?

Describe how the new functionalities can be tested by PR reviewers

## How have functionalities been implemented?

Describe how the new functionalities have been implemented by the
changed code at a high level

## Any issues with implementation?

Describe any problems with your implementation

## Any changes to automated tests?

Describe any automated tests that have been developed for the new 
functionalities

## Any changes to documentation?

Describe changes to the documentation

## Any technical debt repayment?

Describe changes to code that repays any technical debt

## Any improvements to CI/CD pipeline?

Describe any improvements to the Gitlab pipeline

2022-07-05 06:34 UTC, pli888 requested changes
See comments in code.

2022-07-05 06:34 UTC, pli888 commented on gigareview/console/migrations/m220629_145450_create_manuscript_table.php
> +            'updated_at' => $this->bigInteger(),
* `revision_number` is not required, and neither is `revison_id`
* Keep `created_at` and `updated_at` for table timestamps
* Need a `publication_date` field
* Need a `doi` field
* Need an `editorial_status_date` field
* Need an `editorial_status` field
* Update ER diagram using omnigraffle

2022-07-05 06:34 UTC, pli888 commented on gigareview/common/tests/unit/ManuscriptTest.php
> +    public function testCanInsertValuesToTable()
This function is not required.

2022-07-05 06:34 UTC, pli888 commented on gigareview/common/models/Manuscript.php
> +class Manuscript extends \yii\db\ActiveRecord
This function needs to be updated according to changes required in `m220629_145450_create_manuscript_table` below.

2022-07-05 13:27 UTC, rija approved these changes
Looks good to me @kencho51

2022-07-06 02:21 UTC, pli888 approved these changes
The code looks good now.

2022-07-07 16:35 UTC, merged