Migration script for transferring datasets from CNGB backup server to Wasabi
gigascience/gigadb-website pull request #1172
Opened 2022-11-30 15:13 UTC by pli888

# Pull request for issue: #1130

This is a pull request for the following functionalities:

* Batch copy of GigaDB dataset files to `live` directory in Wasabi `gigadb-website` bucket
* Default test mode that copies files to `gigadb-website/dev` bucket directory
* Logging of status messages
* Docker deployment of dataset migration tool on CNGB backup server

## How to test?

See [README](https://github.com/pli888/gigadb-website/blob/rclone-cngb2wasabi/gigadb/app/tools/wasabi-migration/README.md) documentation.

## How have functionalities been implemented?

Describe how the new functionalities have been implemented by the
changed code at a high level

## Any issues with implementation?

Describe any problems with your implementation

## Any changes to automated tests?

Describe any automated tests that have been developed for the new 
functionalities

## Any changes to documentation?

Describe changes to the documentation

## Any technical debt repayment?

Describe changes to code that repays any technical debt

## Any improvements to CI/CD pipeline?

Describe any improvements to the Gitlab pipeline

2022-12-01 07:48 UTC, kencho51 commented on gigadb/app/tools/wasabi-migration/generate_config.sh
> +TARGET=${APP_SOURCE}/config/rclone.conf
Hi @pli888,

`${APP_SOURCE}/config/` is not present, when `% docker-compose run --rm config` would get this error:
```
+ SOURCE=/app/rclone.conf.dist
+ TARGET=/app/config/rclone.conf
+ VARS='$WASABI_ACCESS_KEY_ID:$WASABI_SECRET_ACCESS_KEY'
+ envsubst '$WASABI_ACCESS_KEY_ID:$WASABI_SECRET_ACCESS_KEY'
/app/generate_config.sh: line 74: /app/config/rclone.conf: No such file or directory
ERROR: 1
```
If `mkdir config` and then `docker-compose run --rm config`, `rclone.conf` would then be generated.

2022-12-01 14:12 UTC, rija requested changes
Hi @pli888,

**praise**: Got functionality working as described in the README file, and the code looks fine to me.

**issue**: In the rclone.conf, the value of the ``acl`` key should be ``public-read``
Otherwise the file can't be downloaded by end users using the public URL

**suggestion**: as already alluded to by @kencho51, it might be a good idea to add ``mkdir config`` in the README file before the line indicating how to generate rclone configuration

**thought**: I see that the max batch size is hard-coded. I wonder whether we might in some situation want to override it using an environment variable

2022-12-02 05:26 UTC, pli888 commented
>issue: In the rclone.conf.dist, the value of the acl key should be public-read
Otherwise the files can't be downloaded by end users using the public URL

>suggestion: as already alluded to by @kencho51, it might be a good idea to add mkdir config in the README file before the line indicating how to generate rclone configuration

>thought: I see that the max batch size is hard-coded. I wonder whether we might in some situation want to override it using an environment variable

All above suggestions have been implemented.

2022-12-02 06:51 UTC, kencho51 commented on gigadb/app/tools/wasabi-migration/README.md
> +```
Hi @pli888,

**non-blocking**: the batch size to 200 => `300`?

2022-12-02 06:53 UTC, kencho51 commented on gigadb/app/tools/wasabi-migration/README.md
> +two datasets which are fouund in the `tests/data/gigadb/pub/10.5524/100001_1010001`
Hi @pli888,

**typo**: should be `found`.

2022-12-02 07:51 UTC, kencho51 approved these changes
Hi @pli888,

**praise:** the logic in the `rclone_copy.sh` considers every environments( dev, staging and live), and allows copying with least human interruption, which means less error.

**praise:** allowing command line options in the `rclone_copy.sh` to optimize the `rclone copy` functionality is elegant.

**thought:** wondering if `--config=` option was allowed the `rclone copy` command, and pointed to customized `rclone.conf` file containing different end points, this tool would then be more versatile as it can copy `from/to` from designated regions.

By following the steps in the readme, the functionalities are working in my local dev environment and in the cngb backup server. And in the cngb backup server, `Migration` user is used, `rclone delete/purge` cmd would result as `Forbidden` or `Access Denied` in the log file when tried to delete files/folders or list non-live directory. And I could see the `--max-batch-size ` is working as well.

The code looks good to me, I'm happy to approve it.

2022-12-02 18:00 UTC, rija requested changes
Hi  @pli888:  

**praise**: suggested changes have been implemented and I tested them working  

**praise**: good idea for logs naming scheme, make it easy where to find the log for a specific run of the tool 

**issue**: The error message on line 130 is not written to the log when exit code is non-zero.  
 
The exit code shows up on the command line, but if it's not in the log, the notification script won't see it. 
Additionally,  the error message string is missing the value of the exit code even though the intent seem to be there (as indicated by the presence of a colon at the end). 

Console output:
```
~/c/p/g/a/t/wasabi-migration►docker-compose run --rm rclone /app/rclone_copy.sh --starting-doi 100001 --ending-doi 100002                                                   4.144s
Creating wasabi-migration_rclone_run ... done
ERROR: 8
```

Logs output: 
```
2022/12/02 17:25:22 ERROR : CR.kegg.gz: Failed to copy: Put "https://s3.ap-northeast-1.wasabisys.com/gigadb-datasets/dev/pub/10.5524/100001_101000/100002/CR.kegg.gz": max transfer limit reached as set by --max-transfer
2022/12/02 17:25:22 ERROR : Cancelling sync due to fatal error: Put "https://s3.ap-northeast-1.wasabisys.com/gigadb-datasets/dev/pub/10.5524/100001_101000/100002/CR.kegg.gz": max transfer limit reached as set by --max-transfer
2022/12/02 17:25:22 ERROR : readme.txt: Failed to copy: RequestCanceled: request context canceled
caused by: context canceled
2022/12/02 17:25:22 ERROR : Fatal error received - not attempting retries
2022/12/02 17:25:22 Failed to copy with 2 errors: last error was: Put "https://s3.ap-northeast-1.wasabisys.com/gigadb-datasets/dev/pub/10.5524/100001_101000/100002/CR.kegg.gz": max transfer limit reached as set by --max-transfer
```

>note: I've artificially created the error mode by adding ``--max-transfer 1KiB \`` parameter to the rclone copy command.

  The problem's root cause is the `set -e` directive at the top that cause the script to exit after rclone has exited meaning any instructions after the rclone command won't be parsed.  
  A possible fix is to add a `set +e` just  before the call to `rclone copy`. That approach allows the top `set -e` to still protect the code block before the call (the operator don't want rclone to be called at all if there is any problem in the code above, and since at that stage the operator is still interacting, there is no need to log those)

2022-12-05 05:06 UTC, pli888 commented
>A possible fix is to add a set +e just before the call to rclone copy

@rija This fix has been added. I confirm the exit code is now written into the log file in case there is a problem with running rclone.

2022-12-05 11:47 UTC, rija approved these changes
Hi @pli888 

**praise**: it looks good to me now. Happy to approve

2022-12-05 17:34 UTC, merged