Use swatchdog to send message to gitter room
gigascience/gigadb-website pull request #1173
Opened 2022-12-03 09:54 UTC by kencho51

# Pull request for issue: #<insert relevant github issue numbers that this PR is related to>

This is a pull request for the following functionalities:

* Describe functionality 1
* Describe functionality 2
* *Etc.*

## How to test?

Describe how the new functionalities can be tested by PR reviewers

## How have functionalities been implemented?

Describe how the new functionalities have been implemented by the
changed code at a high level

## Any issues with implementation?

Describe any problems with your implementation

## Any changes to automated tests?

Describe any automated tests that have been developed for the new 
functionalities

## Any changes to documentation?

Describe changes to the documentation

## Any technical debt repayment?

Describe changes to code that repays any technical debt

## Any improvements to CI/CD pipeline?

Describe any improvements to the Gitlab pipeline

2022-12-15 06:31 UTC, pli888 commented on gigadb/app/tools/wasabi-migration/Dockerfile
> +        swatch \
I would prefer that the Swatchdog Docker service be created by a simpler `Swatchdog-Dockerfile` which just contains the `swatch` tool installed and has a `CMD` attribute which returns the version of Swatchdog installed.

2022-12-15 06:41 UTC, pli888 commented on gigadb/app/tools/wasabi-migration/docker-compose.yml
> +    command: /app/spin_up_swatchdog.sh
It feels confusing to use the `rclone` service to create the Swatchdog container and start the tool. I think it's better to have a specific Swatchdog Docker service called something like `rclone_monitor` to be defined in `docker-compose.yml`. You could even think about starting the Swatchdog service in `docker-compose.yml` using something similar to below:
```
command: swatchdog -c /app/config/swatchdog.conf -r $RESTART_TIME -t "$$(cat /app/logs/latest_rclone_log)"
```

2022-12-16 05:38 UTC, pli888 commented on gigadb/app/tools/wasabi-migration/README.md
> +Creating wasabi-migration_rclone_cngb_1 ... done
I am able to manually execute these commands to see the functionality working. I wonder if these commands would be better placed in a bash script for execution? The bash script would contain logic to check if a Swatchdog container is already running and, if so, then could use `docker restart` to get it to monitor the latest rclone_copy log file. If not, then the script would spin up a new Swatchdog container. I also wonder if it is a good idea to use `&&` to chain the commands together. If `rclone_copy` is long running then Swatchdog would not run until `rclone_copy` process has finished which could take days? Probably best that the Swatchdog container starts monitoring as soon as the new log file is present.

2022-12-21 16:15 UTC, rija requested changes
Hi @kencho51,

After doing:
```
cp env.example .env
```
And filling in the appropriate information, I was able to proceed with the "How to test section"

**praise**: I was able to follow through and the outcome in both scenarios (using the distinct commands and then using the wrapper script) led to appropriate entry in the log and appropriate notification appearing in the Gitter channel

**issue**: the following line (which is used three times) is dangerous because it's trying to stop any running docker containers, even those that have nothing to do with the "wasabi-migration_swatchdog" service. Because you are not running other containers, don't assume it's the case for the other developers (or a future you)
```
docker stop "$(docker ps -aq)" && docker rm "$(docker ps -aq)"
```

It's better to act on the particular service you want to stop:
```
docker-compose stop swatchdog || true
```
(You can still use ``up -d`` after the service has been stopped that way to restart it)

In general, when possible, avoid mixing usage of ``docker`` and ``docker-compose``, because their scope of operation is different. The latter is limited to the directory/context of where the docker-compose file is and is application/service level. The former is global and lower-level.

**issue (non-blocking)**: With Bash ``if`` conditional statement, it is thrown upon to have the ``then`` on a separate line.

Check out the examples:

* in Bash's official documentation: https://www.gnu.org/software/bash/manual/html_node/Conditional-Constructs.html
* And in the Linux documentation project: https://tldp.org/HOWTO/Bash-Prog-Intro-HOWTO-6.html

**question**: When I run the wrapper I got this output:
```
$ ./start_backup_process.sh 100001 100320 100
Error response from daemon: 404 page not found
wasabi-migration_swatchdog_1 is up-to-date
Creating wasabi-migration_rclone_run ... done
Error response from daemon: 404 page not found
```

I don't know what those "404 page not found" errors are doing here?
I think it is related to the dangerous line mentioned above.

**question**: in the final housekeeping statement,  the dangerous line can be replaced with ``docker-compose rm -fsv wasabi-migration_watchdog``
But I'm not sure the value of removing the service, since we may need to start the process multiple time?

2022-12-22 09:16 UTC, kencho51 commented
Hi @rija,

> But I'm not sure the value of removing the service, since we may need to start the process multiple time?

In the latest commits, the swatchdog service will be stopped instead of removing because it is meant to be started several times. If the variables `devBackupStatus` , `liveBackupStatus` are not empty and equals to `0`, the swatchdog service will be stopped. 

And the error `Error response from daemon: 404 page not found` has been fixed after placing the `then` at the same line as the if clause.

2023-01-04 13:41 UTC, rija approved these changes
Hi @kencho51, 
happy about the changes.
Providing that @pli888 has reviewed this and successfully tested it on CNGB infrastructure, I'm happy to approve.

2023-01-05 03:49 UTC, pli888 commented on gigadb/app/tools/wasabi-migration/start_backup_process.sh
> +    fi
Does the indentation need fixing in lines 31-33?

2023-01-05 03:55 UTC, pli888 approved these changes
I can get the functionality working on the CNGB backup server and the code looks fine to me - just take a look at my comment re: indentation and this PR can be merged.

2023-01-05 19:54 UTC, merged