Retrieve datacite text using try catch
gigascience/gigadb-website pull request #1187
Opened 2023-01-04 08:28 UTC by kencho51

# Pull request for issue: #1056

This is a pull request for the following functionalities:

* Describe functionality 1
* Describe functionality 2
* *Etc.*

## How to test?

Describe how the new functionalities can be tested by PR reviewers

## How have functionalities been implemented?

Describe how the new functionalities have been implemented by the
changed code at a high level

## Any issues with implementation?

Describe any problems with your implementation

## Any changes to automated tests?

Describe any automated tests that have been developed for the new 
functionalities

## Any changes to documentation?

Describe changes to the documentation

## Any technical debt repayment?

Describe changes to code that repays any technical debt

## Any improvements to CI/CD pipeline?

Describe any improvements to the Gitlab pipeline

2023-02-06 09:34 UTC, pli888 commented on protected/views/dataset/view.php
> +                                                $webClient = new GuzzleHttp\Client();
If we want to fetch information from an external source such as DataCite - this functionality is related to what the [DownloadService](https://github.com/gigascience/gigadb-website/blob/develop/protected/components/DownloadService.php) component class provides?

2023-02-07 05:26 UTC, pli888 reviewed
There are two parts to this PR:
  * Conditional display of the `Cite Dataset` button based on whether citation for the dataset can be fetched from a [datacite.org](http://datacite.org/) URL containing the dataset identifier. If URL is not resolvable, e.g. 404 error message then error is caught and button is not displayed.
  * Display citation for the manuscript publication reporting the dataset in the Additional details section. The manuscript citation comes from https://doi.org/. If the [doi.org](http://doi.org/) URL does not work with the manuscript identifier then the error is caught and dataset page is displayed instead of hanging.

**praise:** The functionality works. To test the PR, I updated dataset 100142's associated manuscript with a fake DOI: 10.1186/s13742-015-9999-9. When I go to http://gigadb.gigasciencejournal.com:9170/dataset/view/id/100142, the new code catches the error when trying to fetch manuscript information and dataset page fully loads.

**praise:** The Cite Dataset button is now not displayed for http://gigadb.gigasciencejournal.com:9170/dataset/300070, because it does not an associated manuscript.

**praise:** All acceptance tests are passing. The functional test is passing.

**issue:** `Read the peer-reviewed publication(s):` is displayed on the dataset page even when there is no manuscript citation in the Additional details section. For example, see http://gigadb.gigasciencejournal.com:9170/dataset/view/id/100142. Is it possible to not have `Read the peer-reviewed publication(s):` displayed when there is no manuscript information to be shown?

2023-02-07 08:48 UTC, only1chunts commented
Hi,
Maybe i'm mis-understanding something here but I would like to claify....
1 - 

> praise: The Cite Dataset button is now not displayed for http://gigadb.gigasciencejournal.com:9170/dataset/300070, because it does not an associated manuscript.

This is not the correct behaviour? The Cite Dataset button has nothing to do with the linked manuscript and should always be displayed.

2 - 

> issue: Read the peer-reviewed publication(s): is displayed on the dataset page even when there is no manuscript citation in the Additional details section. For example, see http://gigadb.gigasciencejournal.com:9170/dataset/view/id/100142. Is it possible to not have Read the peer-reviewed publication(s): displayed when there is no manuscript information to be shown?

100142 does have a linked manuscript in live, so unless its been deleted from this test server then there should be something displayed.

2023-02-07 13:57 UTC, kencho51 commented
Hi @only1chunts,

> This is not the correct behaviour? The Cite Dataset button has nothing to do with the linked manuscript and should always be displayed.

The `Cite Dataset` button on dataset page will try to retrieve citation information from `https://data.datacite.org/$identifier`, if the link is broken, `404 Not Found` would be resulted when `Text` is clicked.
Take this url (https://data.crosscite.org/text/x-bibliography/10.5524/109999)  as an example, you would get  get this error `The resource you are looking for doesn't exist.` 
By hiding the `Text` option can prevent someone seeing that error page. For the same reason, the options for `RIS` (https://data.crosscite.org/application/x-research-info-systems/10.5524/109999) and `BibTex` ( https://data.crosscite.org/application/x-bibtex/10.5524/109999) could also be hidden. So, as a result, hiding the `Cite Dataset` button seems to be a fix for all.

2023-02-07 15:24 UTC, only1chunts commented
There is something very off with this ticket. I think we need to discuss the actions as it doesn't all make sense. The two parts to this ticket are completely separate, yet they are being merged together here which makes it impossible to tell which fixes/tests are for which of the issues.
The Cite Dataset Button has nothing to do with manuscript links, so why does the manual test say "change the manuscript link in the admin page and look at the Cite dataset button on the staging server"? this is not logical as they are unrelated so one should not affect the other. If it does then we have a problem.
Maybe the implemented functions are correct, i.e. If any call to datacite fails then dont show that part of the page, but the testing of it is definately questionable.

2023-02-08 05:16 UTC, pli888 commented
@only1chunts I think the PR could have been better written so it is more clearer. The way I understand it is that this PR is to do with fixing the display of the manuscript citation in a dataset page in the Additional information section. The work to do with the `Cite Dataset` button and its manual testing is technical debt repayment and would have been better placed under this heading in the PR.

2023-02-08 05:21 UTC, pli888 commented on tests/acceptance/DatasetView.feature
> +  @ok @issue-1056
In a few months time, I will have forgotten what issue 1056 was about. I think a better tag to use would be something like `@cite-dataset-button`

2023-02-13 17:38 UTC, rija reviewed
**praise:** successfully replicated the instructions in "How to test" sections
**praise:** the new functional tests and acceptance tests scenarios pass and look fine to me
**issue:**  broken publication links should not be present in the returned array
the `getPublications()` function return a list of links to be ultimately shown by the view for display, if there is no link nothing is displayed,
If a link has a problem (and therefore caught by a try...catch block), it should not be part of the returned array.
As it stands now, I think there still is a link row added to the array even if the publication link has errored. That's the probable cause of the issue @pli888 referred to
**polish:** check PSR12 on `protected/components/StoredDatasetConnections.php`, `protected/views/dataset/view.php`, and `tests/_support/AcceptanceTester.php`

2023-02-13 20:17 UTC, rija reviewed
**praise:** good job moving most of the legacy tests over to Codeception

2023-02-14 08:37 UTC, kencho51 commented
Hi @pli888 and @rija,

By adding condition `&& null !== $publications['citation']` [5db2a50](https://github.com/gigascience/gigadb-website/pull/1187/commits/5db2a50903b38b12c9882ccc7d86826d6a8d7191) in the `/protected/view/dataset/view.php`, the `Read the peer-reviewed publication(s):` on the dataset page now will be hidden if the link is broken.

But the array returned by the `getPublications()` still contains the ['citation'] entry with empty value.

2023-02-14 09:43 UTC, rija commented
@kencho51 remember the try/catch is inside a loop, if you end up in a catch block you should skip that iteration, no reason to perform the rest  of the loop block in that case. It's not correct to return an array with dodgy data in it

2023-02-15 09:19 UTC, kencho51 commented
Hi @rija,


> @kencho51 remember the try/catch is inside a loop, if you end up in a catch block you should skip that iteration, no reason to perform the rest of the loop block in that case. It's not correct to return an array with dodgy data in it

In this [eb9e76f](https://github.com/gigascience/gigadb-website/pull/1187/commits/eb9e76fb9ff0f71177550d6c546b9868fdd7239c), the loop is inside the try/catch block, so if there is an exception, the loop would be skipped and the array returned would be empty.

The functional test and the unit test have been updated aw well.

2023-02-15 14:24 UTC, rija commented
Hi @kencho51,

I think putting the try/catch block outside a loop may cause problems:
If we have a list of links, and the first link is problematic, an Exception will trigger the catch block which is outside the loop.
That means, that none of the remaining links will make it to the global returned array, which is not good.

When I said "you should skip that iteration", I meant it literally, using the [continue](https://www.php.net/manual/en/control-structures.continue.php) directive.

2023-02-20 16:22 UTC, rija requested changes
Hi @kencho51,

**praise:** Can see only working links are returned to the views from domain layer for publication links
**issue:** there is block of code in `protected/views/dataset/view.php` that still has the potential to blow up to the user screen:

```
 57.   $textFileExist = DownloadService::fileExists($url);
 58.  if ($textFileExist) {
 59.  	$textFile = DownloadService::downloadFile($url);
```
If a network failure happen between the moment line 57 is executed and the moment line 59 is executed, an uncaught exception will be displayed to the user 
Because `DownloadService::downloadFile` throws a generic PHP exception (which is also not optimal) and the view code is not catching it.
**suggestion:** One way out of it, is you could forgo the use of `DownloadService::fileExists` and just wrap line 59 in try/catch
With the `$showButton = false;` in the catch block, and the `$showButton = true;` in the try block

`DownloadService::downloadFile()` throws a generic PHP Exception, which could be then one you need to catch, but it's not the correct exception for it to throw.
Ideally, in that function (I know it's not code you wrote, but I missed it last time), we should check using a `switch case` block, the different response codes (not just 200 vs everything else) and then throw the appropriate exception as listed here: https://docs.guzzlephp.org/en/stable/quickstart.html#exceptions
But an easier and still correct for now implementation would be to throw `GuzzleHttp\Exception\BadResponseException` instead of the generic PHP exception and catch it in the code in `protected/views/dataset/view.php`
You DON'T need to modify `protected/commands/FilesCommand.php`'s `actionUpdateMD5FileAttributes()`, the original function that needed `DownloadService::downloadFile()`, because that function is somehow catching `\GuzzleHttp\Exception\GuzzleException` which is the interface also implemented by `GuzzleHttp\Exception\BadResponseException`'s parent class, so the suggested change will still work with that code (because of the L in SOLID principles)

2023-02-22 02:21 UTC, kencho51 commented
Hi @rija and @pli888 ,

The `downloadFile()` has been updated to throw `GuzzleHttp\Exception\BadResponseException`, and it will be caught in the `protected/views/dataset/view.php`.

Although the `downloadFile()` function may throw other `GuzzleException`, the caller method needs to have  a catch block to handle it, such as `actionUpdateMD5FileAttributes()` already has one.

So, please have a look of this PR again.

2023-02-23 18:39 UTC, rija approved these changes
Hi @kencho51

praise: the code and usage of `throw` and `try...catch` in the `DownloadService` and the view look good to me
praise: the `DownloadService`'s `downloadFile()` method now throws a relevant exception

LGTM, happy to approve

2023-02-27 11:12 UTC, pli888 approved these changes
**praise:** I can see the downloadFile function in DownloadService class now returns a more appropriate BadResponseException if the response status code is not 200. The BadResponseException will be caught in the dataset view class if it fails to retrieve citation data for a manuscript from DataCite and disable display of the cite dataset button due to the `showButton` Boolean variable being false.

@kencho51 I approve this PR.

2023-02-27 15:22 UTC, merged