Use files-metadata-console to update dataset file locations with Wasabi URLs
gigascience/gigadb-website pull request #1294
Opened 2023-06-12 05:24 UTC by pli888

# Pull request for issue: #<insert relevant github issue numbers that this PR is related to>

This is a pull request for the following functionalities:

* Describe functionality 1
* Describe functionality 2
* *Etc.*

## How to test?

Describe how the new functionalities can be tested by PR reviewers

## How have functionalities been implemented?

Describe how the new functionalities have been implemented by the
changed code at a high level

## Any issues with implementation?

Describe any problems with your implementation

## Any changes to automated tests?

Describe any automated tests that have been developed for the new 
functionalities

## Any changes to documentation?

Describe changes to the documentation

## Any technical debt repayment?

Describe changes to code that repays any technical debt

## Any improvements to CI/CD pipeline?

Describe any improvements to the Gitlab pipeline

2023-06-29 07:40 UTC, kencho51 requested changes
Hi @pli888,

**praise:** The file urls can be replaced with the supplied prefix in both my dev, staging and live.
**praise:** It is great to the command is executed in dry run mode by default.
**praise:** The readme is well documented.
**praise:** Great to have unit test working after adding `Db` module to the unit test suite, the gigadb_testdata database can be restored after each test.
**issue(typo):** In readme file, line 343, the test DatasetFilesURLUpdaterTest.php`:^testReplaceFileUrlSubstringWithPrefix$` does not exist.
**issue(typo):** In readme file, line 352, `:^tryStopDoi$` should be removed as it is trying to run all tests. 
**question:** What is the purpose of having `--prefix=` parameter in the command? The actual prefix has been determined by the `$newFTPLocationPrefix` in the function `replaceFileLocationsForDataset` and `$newFTPSitePrefix` in the function `replaceFTPSiteForDataset` already. For example, I tried `% docker-compose run --rm files-metadata-console ./yii update/urls --prefix=https://test.com --separator=/pub/ --next=3 --exclude='100020,100039' --apply`, the command can be executed successfuly and the `ftp_site` and `location` will still be replaced by the prefix hard coded in the `DatasetFilesURLUpdater` component class.
**suggestion:** Do not make the `--prefix=` as a mandatory option or perform checking whether the supplied prefix equals to the expected one.
**issue(non-blocking):** After the url replacement, there is no indication of changes, for example, `update at` or `modified at` in the tables.
**suggestion(non-blocking):** Would it be worthy to bring in `update at` or `modified at` in `dataset` table and `file` table in this PR?
**suggestion(non-blocking):** In `replaceFTPSiteForDataset` function, there is a counter parameter `$success`, should change it to `$processed` as in the `replaceFileLocationsForDataset` for the consistency?
**suggestion(non-blocking):** Update the `CHANGELOG` when PR #1287 has been merged.

2023-07-11 09:55 UTC, rija requested changes
Hi @pli888,

**praise**: the batched, safe migration of URLs works fine locally and on my AWS deployment
**praise**: Great that more models classes are added to `gigadb/app/models`
**praise**: Good use of the factory pattern for instantiating `DatasetFilesURLUpdater`
**praise**: Terrific work on the automated test infrastructure for unit and functional test suite

**issue**: after running the url replacement script,  the `ftp_site` link on the dataset page shows a permission error
**suggestion**: as discussed with Chris H, let's remove the ftp_site link from the dataset page as we cannot link to directories on Wasabi for non-Wasabi users

**issue**: The container images created in `gitlab-config-(staging|live)-build.yml`  and `gitlab-config-(staging|live)-deploy` for the `files-metadata-console` project have the wrong tag (`latest`) applied to them. The consequence is, because the configuration settings are baked into the image, we can't distinguish between `staging` an `live` configuration and that may cause subtle but high impact data incident when in use in production.
I guess we were lucky so far at the moment probably because we use the same data on staging and beta live for now and don't use both environment at the same time, but it's going to bite us soon enough.
**suggestion**: use $GIGAB_ENV as tag

**issue**: there is a constant `BUCKET_DIRECTORIES` that hard-code the `live` environment. This is not correct as testing the script on staging environment may impact the live environment. 
**suggestion**: pull the Gigadb environment from environment variable which can then be added to `gigadb/app/tools/files-metadata-console/config/params.php` by the means of new `params.php.dist` in template directory `gigadb/app/tools/files-metadata-console/config-sources`

**issue(non-blocking**): the `--prefix` command line option is actually not necessary because its value doesn't change often when we use the command line (it's only change when we change cloud providers which should be rare occurrence) **suggestion**: Either create a constant (e.g URL_PREFIX) in the controller class or better create an environment variable (in case it's not as rare occurrence as I think it is - e.g: multi-cloud, backups, ....) which can be added to `gigadb/app/tools/files-metadata-console/config/params.php` by the means of new `params.php.dist` in template directory`gigadb/app/tools/files-metadata-console/config-sources`


**issue (caching, non-blocking)**: When I followed the testing instructions for the staging environment, the first dataset processed (10001) was logged as done, but it the dataset page was only partially updated (the ftp site link had the correct updated link, but the file locations were all still pointing to the old ftp server). 
**suggestion**: In the SOP for this tool, we should probably add a final step to restart the web app to reset the cache to be safe. Also, if you are able to reproduce it, you could create a Github ticket so we can later investigate our caching validation code

**issue(test, non-blocking)**: Prefixing the shell command in the functional tests with `echo yes |` is not necessary because the command doesn't prompt user for input (which are the scenarios that kind of prefix is meant for)
**issue(test, non-blocking)**: I was surprised to see several of the functional tests have assertions for file locations containing reference to  DOI `100020` which I believed is **not** in `gigadb_testdata`. I then noticed that those files are attached to dataset of id 211 (DOI 100003). It's a bit confusing, so It would be nice to ensure all the file locations for dataset 100003 reference its DOI and not some other DOIs.

**Issue (non-blocking)**: The methods `updateDbDatasetTable()` and `updateDbFileTable()` are extra code that are not necessary
**suggestion**: alternatives:
The code 
```
$this->updateDbDatasetTable($newFTPSite, $dataset->id);
```
Can be written as (not sure the exact syntax for getLastError, check Yii docs):
```
$dataset->ftp_site =  $newFTPSite ;
$dataset->save() || throw new Exception($dataset->getLastError()); 
```

And the code
```
$this->updateDbFileTable($newFileLocation, $file->id);
```
Can be written as
```
$file->location = $newFileLocation;
$file->save() || throw new Exception($file->getLastError());
```

2023-07-22 02:45 UTC, pli888 commented
>issue(typo): In readme file, line 343, the test DatasetFilesURLUpdaterTest.php:^testReplaceFileUrlSubstringWithPrefix$ does not exist.
>issue(typo): In readme file, line 352, :^tryStopDoi$ should be removed as it is trying to run all tests.

These two typos have been corrected in README.md.

>question: What is the purpose of having --prefix= parameter in the command? The actual prefix has been determined by the $newFTPLocationPrefix in the function replaceFileLocationsForDataset and $newFTPSitePrefix in the function replaceFTPSiteForDataset already. For example, I tried % docker-compose run --rm files-metadata-console ./yii update/urls --prefix=https://test.com --separator=/pub/ --next=3 --exclude='100020,100039' --apply, the command can be executed successfuly and the ftp_site and location will still be replaced by the prefix hard coded in the DatasetFilesURLUpdater component class.
suggestion: Do not make the --prefix= as a mandatory option or perform checking whether the supplied prefix equals to the expected one.

The code has been updated so that the --prefix parameter is not required now.

> issue(non-blocking): After the url replacement, there is no indication of changes, for example, update at or modified at in the tables.
suggestion(non-blocking): Would it be worthy to bring in update at or modified at in dataset table and file table in this PR?

As discussed at a recent VOH, this work will be done in a more holistic manner in the future.

>suggestion(non-blocking): In replaceFTPSiteForDataset function, there is a counter parameter $success, should change it to $processed as in the replaceFileLocationsForDataset for the consistency?

I've not made any code changes - the variable names seem clear to me.

>suggestion(non-blocking): Update the CHANGELOG when PR https://github.com/gigascience/gigadb-website/pull/1287 has been merged.

CHANGELOG.md has been updated with an unreleased section. Maybe @rija can update CHANGELOG.md when this PR has been merged.

2023-07-22 02:58 UTC, pli888 commented
>issue: after running the url replacement script, the ftp_site link on the dataset page shows a permission error
suggestion: as discussed with Chris H, let's remove the ftp_site link from the dataset page as we cannot link to directories on Wasabi for non-Wasabi users

The view class for datasets has been updated so dataset pages do not display FTP site link now.

>issue: The container images created in gitlab-config-(staging|live)-build.yml and gitlab-config-(staging|live)-deploy for the files-metadata-console project have the wrong tag (latest) applied to them. The consequence is, because the configuration settings are baked into the image, we can't distinguish between staging an live configuration and that may cause subtle but high impact data incident when in use in production.
I guess we were lucky so far at the moment probably because we use the same data on staging and beta live for now and don't use both environment at the same time, but it's going to bite us soon enough.
suggestion: use $GIGAB_ENV as tag

The $GIGADB_ENV tag is now used to tag and select container images in the build and deploy yml files. The $GIGADB_ENV tag is also now required in order to identify which container image to use in order to use the files metadata console tool.

>issue: there is a constant BUCKET_DIRECTORIES that hard-code the live environment. This is not correct as testing the script on staging environment may impact the live environment.
suggestion: pull the Gigadb environment from environment variable which can then be added to gigadb/app/tools/files-metadata-console/config/params.php by the means of new params.php.dist in template directory gigadb/app/tools/files-metadata-console/config-sources

Developers will now need to create a Gitlab secret variable called `DEPLOYMENT_ENV=dev` for dev environment in gigadb-website project-level if they have not already done so.
The `DEPLOYMENT_ENV` variable has been added into `params.php.dist` and is used to create Wasabi bucket path for file location and FTP site URLs instead of using hard-coded URL in BUCKET_DIRECTORIES constant.

>issue(non-blocking): the --prefix command line option is actually not necessary because its value doesn't change often when we use the command line (it's only change when we change cloud providers which should be rare occurrence) suggestion: Either create a constant (e.g URL_PREFIX) in the controller class or better create an environment variable (in case it's not as rare occurrence as I think it is - e.g: multi-cloud, backups, ....) which can be added to gigadb/app/tools/files-metadata-console/config/params.php by the means of new params.php.dist in template directorygigadb/app/tools/files-metadata-console/config-sources

A Gitlab secret variable called `URL_PREFIX=https://s3.ap-northeast-1.wasabisys.com/` has been created in Forks and Upstream. For dev testing, you will need to re-run `docker-compose run --rm configure` to update `.secrets` with URL_PREFIX variable. The URL_PREFIX parameter is now used in DatasetFilesURLUpdater component class. Finally, use of `--prefix` as a command line parameter in UpdateController class and in tests have been removed.

>issue (caching, non-blocking): When I followed the testing instructions for the staging environment, the first dataset processed (10001) was logged as done, but it the dataset page was only partially updated (the ftp site link had the correct updated link, but the file locations were all still pointing to the old ftp server).
suggestion: In the SOP for this tool, we should probably add a final step to restart the web app to reset the cache to be safe. Also, if you are able to reproduce it, you could create a Github ticket so we can later investigate our caching validation code

I confirm that if you visit http://gigadb-staging.gigatools.net/dataset/100001 on your web browser before and after updating its file location URLs using the files metadata console tool, you will see that its file location links always begin with https://ftp.cngb.org/. However, if you browse http://gigadb-staging.gigatools.net/dataset/100002 only after updating its file location URLs, you will see that dataset 100002 page contains file links to https://s3.ap-northeast-1.wasabisys.com/gigadb-datasets. This suggests that there is an issue with the caching validation code. A Github ticket has been created - see https://github.com/gigascience/gigadb-website/issues/1335.

README.md updated with documentation to restart web application after using this tool when on AWS environment.

>issue(test, non-blocking): Prefixing the shell command in the functional tests with echo yes | is not necessary because the command doesn't prompt user for input (which are the scenarios that kind of prefix is meant for)

echo yes | has been removed from shell commands in functional tests.

>issue(test, non-blocking): I was surprised to see several of the functional tests have assertions for file locations containing reference to DOI 100020 which I believed is not in gigadb_testdata. I then noticed that those files are attached to dataset of id 211 (DOI 100003). It's a bit confusing, so It would be nice to ensure all the file locations for dataset 100003 reference its DOI and not some other DOIs.

File locations URLs for dataset 100003 in gigadb_testdata have been updated with more intuitive links.

>Issue (non-blocking): The methods updateDbDatasetTable() and updateDbFileTable() are extra code that are not necessary
suggestion: alternatives:

The changes have been implemented but there is no getLastError() method for active record objects. Instead, I've opted to return all attribute errors as a string which will be useful information.

2023-07-26 10:21 UTC, rija reviewed
Hi @pli888,

**praise**: the code change looks fine
**praise**: the tool works as expected on my local deployment
**issue**: on staging, when I run 
```
docker run --rm "registry.gitlab.com/gigascience/forks/rija-gigadb-website/production-files-metadata-console:staging" ./yii update/urls --separator=/pub/ --exclude='100375,100396,100446,100584,100747,100957,102311' --stop=200002 --next=30 --apply
```
 I got the following error: 
```
	Transforming file locations for dataset 100027...
yii\base\ErrorException: Array to string conversion in /gigadb/app/tools/files-metadata-console/components/DatasetFilesURLUpdater.php:118
Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleError(2, 'Array to string...', '/gigadb/app/too...', 118)
#1 /gigadb/app/tools/files-metadata-console/components/DatasetFilesURLUpdater.php(118): implode(Array)
#2 /gigadb/app/tools/files-metadata-console/controllers/UpdateController.php(121): app\components\DatasetFilesURLUpdater->replaceFileLocationsForDataset('100027', '/pub/')
#3 [internal function]: app\controllers\UpdateController->actionUrls()
#4 /gigadb/app/tools/files-metadata-console/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#5 /gigadb/app/tools/files-metadata-console/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#6 /gigadb/app/tools/files-metadata-console/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction('urls', Array)
#7 /gigadb/app/tools/files-metadata-console/vendor/yiisoft/yii2/base/Module.php(552): yii\console\Controller->runAction('urls', Array)
#8 /gigadb/app/tools/files-metadata-console/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('update/urls', Array)
#9 /gigadb/app/tools/files-metadata-console/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('update/urls', Array)
#10 /gigadb/app/tools/files-metadata-console/vendor/yiisoft/yii2/base/Application.php(384): yii\console\Application->handleRequest(Object(yii\console\Request))
#11 /gigadb/app/tools/files-metadata-console/yii(20): yii\base\Application->run()
#12 {main}
** Rolling back transaction
PHP Warning 'yii\base\ErrorException' with message 'Array to string conversion'

in /gigadb/app/tools/files-metadata-console/components/DatasetFilesURLUpdater.php:118

Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleError(2, 'Array to string...', '/gigadb/app/too...', 118)
#1 /gigadb/app/tools/files-metadata-console/components/DatasetFilesURLUpdater.php(118): implode(Array)
#2 /gigadb/app/tools/files-metadata-console/controllers/UpdateController.php(121): app\components\DatasetFilesURLUpdater->replaceFileLocationsForDataset('100027', '/pub/')
#3 [internal function]: app\controllers\UpdateController->actionUrls()
#4 /gigadb/app/tools/files-metadata-console/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#5 /gigadb/app/tools/files-metadata-console/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#6 /gigadb/app/tools/files-metadata-console/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction('urls', Array)
#7 /gigadb/app/tools/files-metadata-console/vendor/yiisoft/yii2/base/Module.php(552): yii\console\Controller->runAction('urls', Array)
#8 /gigadb/app/tools/files-metadata-console/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('update/urls', Array)
#9 /gigadb/app/tools/files-metadata-console/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('update/urls', Array)
#10 /gigadb/app/tools/files-metadata-console/vendor/yiisoft/yii2/base/Application.php(384): yii\console\Application->handleRequest(Object(yii\console\Request))
#11 /gigadb/app/tools/files-metadata-console/yii(20): yii\base\Application->run()
#12 {main}
[centos@ip-10-99-0-14 ~]$ 
```
**praise**: When I add the problematic DOI above to the exclude list, the tool is working fine and after triggering `sd_gigadb` on the gitlab pipeline, the website reflects the expected changes on staging.
**praise**: good idea adding an "Unreleased" section to the CHANGELOG. I think we should keep adding our PR headline in there for now until we've figured out a proper release management

2023-08-02 02:05 UTC, kencho51 commented
Hi @pli888,

When I tried to spin up `files-metadata-console` tool, I got this error:
```
% ./up.sh
% cd gigadb/app/tools/files-metadata-console
% ./configure
% docker-compose run --rm composer composer install
WARN[0000] a network with name deployment_db-tier exists but was not created for project "files-metadata-console".
Set `external: true` to use an existing network 
network deployment_db-tier was found but has incorrect label com.docker.compose.network set to "db-tier"
```

It seems the `docker-compose.yml` is trying to create a network inside the `files-metadata-console` application, which is not the intentional usage. This can be fixed by adding `external` parameter to the docker-compose file as below:
```
networks:
  proxy-db-tier:  # represents db-tier network in ops/docker-compose.yml
    name: deployment_db-tier
    external: true
 ```

Therefore, as a result, the would use the existing external network `deployment_db-tier`, instead of creating a new one.

Details of the `external` parameters can be found at https://docs.docker.com/compose/networking/#use-a-pre-existing-network

2023-08-15 06:31 UTC, pli888 commented
@rija

>I got the following error:
```
Transforming file locations for dataset 100027...
yii\base\ErrorException: Array to string conversion in /gigadb/app/tools/files-metadata-console/components/DatasetFilesURLUpdater.php:118
```

This error has been fixed by updating the location validation rule in the File model class.

2023-08-22 12:52 UTC, pli888 commented
>docker-compose run --rm files-metadata-console ./vendor/codeception/codeception/codecept run --debug tests/functional/ReplaceFileUrlSubstringWithPrefixCest.php

Functional tests are passing again now. If you are running Docker Desktop version 4.22.0 on your Mac then you will probably have to uncomment the `external: true` option in the files-metadata-console docker-compose.yml file.

As discussed in today's VOH, the work to fix the external option error below will be done in a later ticket to expedite merging of current PRs:
```
$ docker-compose run --rm files-metadata-console ./vendor/codeception/codeception/codecept run --debug tests/functional/ReplaceFileUrlSubstringWithPrefixCest.php
WARN[0000] a network with name deployment_db-tier exists but was not created for project "files-metadata-console".
Set `external: true` to use an existing network 
network deployment_db-tier was found but has incorrect label com.docker.compose.network set to "db-tier"
```

As it stands, the File location URL update tool in files-metadata-console works on production data using this command:
```
# 100310 has too many files (19,981) and causes memory error
# 100396 has too many files (197,214) and causes memory error
# 100608 has too many files (12,864) and causes memory error
# 100707 has too many files (16,675) and causes memory error
$ docker run --rm "registry.gitlab.com/$GITLAB_PROJECT/production-files-metadata-console:$GIGADB_ENV" ./yii update/urls --separator=/pub/ --stop=200002 --next=25 --exclude='100310,100396,100608,100707' --apply
```

The excluded datasets will therefore require manual SQL commands to update dataset FTP site and File location links.

2023-08-27 17:10 UTC, rija approved these changes
Hi @pli888,
I can see that all the requested changes have been implemented.
All the tests are passing for me locally and on CI
I'm happy to approve it.

2023-08-29 13:19 UTC, merged