Revise database recovery procedures
gigascience/gigadb-website pull request #1316
Opened 2023-06-28 22:35 UTC by pli888

# Pull request for issue: #<insert relevant github issue numbers that this PR is related to>

This is a pull request for the following functionalities:

* Describe functionality 1
* Describe functionality 2
* *Etc.*

## How to test?

Describe how the new functionalities can be tested by PR reviewers

## How have functionalities been implemented?

Describe how the new functionalities have been implemented by the
changed code at a high level

## Any issues with implementation?

Describe any problems with your implementation

## Any changes to automated tests?

Describe any automated tests that have been developed for the new 
functionalities

## Any changes to documentation?

Describe changes to the documentation

## Any technical debt repayment?

Describe changes to code that repays any technical debt

## Any improvements to CI/CD pipeline?

Describe any improvements to the Gitlab pipeline

2023-08-11 17:03 UTC, rija requested changes
Hi @pli888,

**praise**: Was able to provision and environment from scratch without errors nor warnings
**praise**: Was able to reproduce `docs/sop/RESTORE_DATABASE_BACKUP_IN_S3.md`
**praise**: Was able to reproduce `docs/sop/RESTORE_DATABASE_AWS_BACKUP.md`
**praise**: Was able to reproduce `docs/sop/RESTORE_DATABASE_AWS_SNAPSHOT.md`
**typo**: I think you mean `selected` here, not `deleted` in `docs/sop/RESTORE_DATABASE_AWS_BACKUP.md:60`
**thought**: On the screen for recreating the instance there is a section called "Availability and durability" with interesting options.
Not be done in this PR, I think at some point we should figure out how to enable those from the Terraform configuration.
I think the "Multi-AZ DB Cluster" option is good to have, but both options may probably have some impact to backup and restore SOPs.
There is already an old GitHub issue #1011 to cover this.
When is the right time to do this ? I don't know, we can talk about this at a future status meeting or planning
**suggestion (non-blocking)**: add a step to choose "single DB instance" for now under that section on both RDS-based SOPs
**thought**: In the future, maybe it's a good idea to enable "Auto minor version upgrade" both in Terraform and when restoring using SOPs
**chore**: Rebasing the branch  and adding an entry to CHANGELOG

2023-08-16 03:18 UTC, kencho51 commented on docs/sop/RESTORE_DATABASE_AWS_BACKUP.md
>  12. In the *Connectivity* box, *Password authentication* should be deleted
Hi @pli888,

*Password authentication* cannot be found in the *Connectivity* box, as below:
![image](https://github.com/gigascience/gigadb-website/assets/64770635/f0a59ec0-3554-4363-ac9a-dc5dd1bd7853)

2023-08-16 08:14 UTC, kencho51 requested changes
Hi @pli888,

**praise:** No errors happened during the process of instantiating the production servers.
**praise:** Could reproduce the steps in the SOPs `RESTORE_DATABASE_BACKUP_IN_S3.md`, `RESTORE_DATABASE_AWS_BACKUP.md` and `RESTORE_DATABASE_AWS_SNAPSHOT.md` on my staging.
**issue:**  There is not `Password authentication` in the `Connectivity` section mentioned in `RESTORE_DATABASE_AWS_BACKUP.md`:60.
**suggestion:** Replace `Connectivity` with `Database authentication` where `Password authentication` is found, if they are the same thing.

2023-08-22 06:28 UTC, rija approved these changes
praise: after application of the fix for the issues commented about, now it LGTM
Happy to approve

2023-08-22 09:23 UTC, merged