Prometheus grafana playbook
gigascience/gigadb-website pull request #1324
Opened 2023-07-10 07:46 UTC by rija

# Pull request for issue: #580

This is a pull request for the following functionalities:

* Describe functionality 1
* Describe functionality 2
* *Etc.*

## How to test?

Describe how the new functionalities can be tested by PR reviewers

## How have functionalities been implemented?

Describe how the new functionalities have been implemented by the
changed code at a high level

## Any issues with implementation?

Describe any problems with your implementation

## Any changes to automated tests?

Describe any automated tests that have been developed for the new 
functionalities

## Any changes to documentation?

Describe changes to the documentation

## Any technical debt repayment?

Describe changes to code that repays any technical debt

## Any improvements to CI/CD pipeline?

Describe any improvements to the Gitlab pipeline

2023-07-25 21:54 UTC, pli888 approved these changes
**praise:** Great work on developing the configuration to deploy and install Grafana, Prometheus server and node exporters into the GigaDB cloud infrastructure.
**praise:** The instructions for testing the functionality of all the monitoring components worked for me using the beta server's staging and live deployments. I also managed to get monitoring working with my own staging server deployment.
**praise:** After reviewing the code, it looks good and understandable to me.
**thought:** At least the `BETA_DEPLOY.md` needs updating with regards to the work in this PR.
**suggestion (non-blocking):** @pli888 or @kencho51 to update `BETA_DEPLOY.md` and test it as a side piece of work in next sprint after this PR is merged. We could also tidy up the documentation as technical debt too, e.g. remove out of date information.

2023-07-31 16:21 UTC, kencho51 requested changes
**praise:** This PR is inspiring, use ansible to configure grafana and prometheus, which I think it brings the `IaC` to another level.
**praise:** Instantiate a new server to collect data from bastion server and webapp server is a good idea, which makes the maintenance easier, and more importantly, the server could be scaled up easily if the no. of services needed to be monitored increased.
**praise:** The `how to test` steps are clear, which allows me  to set up the whole infrastructure in staging for testing.
**praise:**  These 3 servers could work well together, the disk full alert could be triggered from the bastion server and the alert email was sent to the defined email address in grafana console.
**suggestion:** Include this PR to the CHANGELOG.
**issue:** In `monitoring_playbook`, there is no ec2_node in ap-northeast-2 region, which is my deploy region.
**suggestion:** Include `ap-northeast-2` region in the monitoring_playbook.
**suggestion(non-blocking):** Agree with @pli888 on updating the documentation, but may be creating `MONITORING.md` is more usable as it is quite a separate task. 
**issue(non-blocking):** When executing the ansible playbooks locally and they would install node\_exporter at the end, got this error: `Make sure the required command to extract the file is installed.\nCommand \"/usr/bin/unzip\" could not handle archive:   End-of-central-directory signature not found.  Either this file is not\n  a zipfile, or it constitutes one disk of a multi-part archive.  In the\n  latter case the central directory and zipfile comment will be found on\n  the last disk(s) of this archive.`.
**suggestion(non-blocking):**  Remind to Install the package `brew install gnu-tar` in mac before .

At last, the code looks good to me.

2023-08-01 15:33 UTC, rija commented
Hi @kencho51, @pli888,
Thanks for reviewing, I've implemented the feedback.

2023-08-02 00:59 UTC, kencho51 approved these changes
Hi @rija,

The updated changes look good to me, so happy to approve this PR.

2023-08-02 09:20 UTC, merged