Provide horizontal scroll bar in files table
gigascience/gigadb-website pull request #1649
Opened 2024-01-15 14:20 UTC by pli888

# Pull request for issue: #<insert relevant github issue numbers that this PR is related to>

This is a pull request for the following functionalities:

* Describe functionality 1
* Describe functionality 2
* *Etc.*

## How to test?

Describe how the new functionalities can be tested by PR reviewers

## How have functionalities been implemented?

Describe how the new functionalities have been implemented by the
changed code at a high level

## Any issues with implementation?

Describe any problems with your implementation

## Any changes to automated tests?

Describe any automated tests that have been developed for the new 
functionalities

## Any changes to documentation?

Describe changes to the documentation

## Any technical debt repayment?

Describe changes to code that repays any technical debt

## Any improvements to CI/CD pipeline?

Describe any improvements to the Gitlab pipeline

2024-01-16 08:03 UTC, luistoptal commented
- praise: I can see the horizontal scroll bar in the page http://gigadb.gigasciencejournal.com/dataset/102484
- note: I can also see the scrollbar in Firefox, but only when overing over the table. Also, the scrollbar is subtler in Firefox

2024-01-16 08:05 UTC, luistoptal approved these changes
- praise: I can see the horizontal scroll bar in the page http://gigadb.gigasciencejournal.com/dataset/102484
- note: I can also see the scrollbar in Firefox, but only when overing over the table. Also, the scrollbar is subtler in Firefox
- note: left a few comments, but I'm happy to approve as it is now

2024-01-16 08:05 UTC, luistoptal commented on less/current/pages/dataset.less
> +#dataset-datatables-wrapper {
nitpick: this works perfectly although it's uncommon to use ids for styling (CSS classes generally preferred), is this a convention we use? i.e. attach styles to unique elements tagged with an id

it looks like a table wrapper that adds a horizontal scrollbar might be a good candidate for a reusable CSS class

FYI the integration branch contains the following which fulfills a similar purpose:

```css
.dataset-table-wide-container {
  overflow-x: auto;
  ...
}
```

2024-01-16 08:05 UTC, luistoptal commented on playwright/README.md
> +## Run tests using Docker
praise: it's amazing that we can now run these tests in a docker container! Nice!

2024-01-16 08:05 UTC, luistoptal commented on playwright/tests/dataset-table-scrollbars.spec.js
> +test('Can scroll horizontally in File table', async ({ page }) => {
praise: passing e2e test

2024-01-16 08:05 UTC, luistoptal commented on protected/views/dataset/view.php
> +                $("#files_table").wrap("<div id='dataset-datatables-wrapper'></div>");
question: is there a reason why this solution is preferred over adding the `<div>` directly in the html? ie.:

```html
<div id='dataset-datatables-wrapper'>
  <table id="files_table" class="table table-striped table-bordered" style="width:100%">
...
  </table>
</div>
```

2024-01-17 04:19 UTC, kencho51 requested changes
Hi @pli888 

**praise:** The scroll bar is presence in the files tab.
**praise:** There is a playwright test for the scroll bar's functionality
**note:** The scroll bar can be seen in firefox when you have ticked all the checkbox in the `Table Settings` 
**praise:** Playwright is containerized, all a11y and e2e tests can be run in a container 
**issue:** When tried to execute `% docker-compose run --rm playwright npm run test` for the first time, would get:
```
[+] Building 0.0s (0/0)                                                                                                                                                                                       docker:desktop-linux
[+] Building 0.0s (0/0)                                                                                                                                                                                       docker:desktop-linux

> e2e@1.0.0 test
> npx playwright test

Need to install the following packages:
playwright@1.41.0
Ok to proceed? (y) 
Error: Cannot find module '@playwright/test'
...
```
**suggestion:**  Add a step in README to install all the dependencies before running the test as :
```
% docker-compose run --rm playwright npm i                  
[+] Building 0.0s (0/0)                                                                                                                                                                                       docker:desktop-linux
[+] Building 0.0s (0/0)                                                                                                                                                                                       docker:desktop-linux

added 5 packages, and audited 6 packages in 1s

found 0 vulnerabilities
```
**issue (non-blocking):** When `% docker-compose run --rm playwright npm run test`, 3 a11y tests failed:
```
...
at /var/www/playwright/tests/accessibility.spec.js:66:83

  3 failed
    [chromium] › accessibility.spec.js:61:7 › Page / › should not have any color contrast issues ───
    [firefox] › accessibility.spec.js:61:7 › Page / › should not have any color contrast issues ────
    [webkit] › accessibility.spec.js:61:7 › Page / › should not have any color contrast issues ─────
  57 passed (39.1s)
```
**suggestion (non-blocking):** @luistoptal would you mind to have a look?

2024-01-19 14:27 UTC, pli888 commented on protected/views/dataset/view.php
> +                $("#files_table").wrap("<div id='dataset-datatables-wrapper'></div>");
When testing the direct addition of `<div>` into the html, there is no horizontal scroll bar displayed in the files table.

2024-01-19 14:34 UTC, pli888 commented on less/current/pages/dataset.less
> +#dataset-datatables-wrapper {
I don't believe it is convention in the code so thanks for the tip. The `dataset-datatables-wrapper` styling is now applied as a CSS class.

2024-01-19 14:58 UTC, pli888 commented
>issue: When tried to execute % docker-compose run --rm playwright npm run test for the first time, would get:

```
[+] Building 0.0s (0/0)                                                                                                                                                                                       docker:desktop-linux
[+] Building 0.0s (0/0)                                                                                                                                                                                       docker:desktop-linux

> e2e@1.0.0 test
> npx playwright test

Need to install the following packages:
playwright@1.41.0
Ok to proceed? (y) 
Error: Cannot find module '@playwright/test'
...
```

@kencho51 When I execute `$ docker-compose run --rm playwright npm run test` for the first time, I don't see the above error. I see this:
```
$ docker-compose run --rm playwright npm run test
[+] Building 322.1s (11/11) FINISHED                                                                      docker:desktop-linux
 => [playwright internal] load build definition from Dockerfile                                                           0.1s
 => => transferring dockerfile: 873B                                                                                      0.0s
 => [playwright internal] load .dockerignore                                                                              0.1s
 => => transferring context: 2B                                                                                           0.0s
 => [playwright internal] load metadata for mcr.microsoft.com/playwright:v1.39.0-focal                                    0.8s
 => [playwright stage-1 1/6] FROM mcr.microsoft.com/playwright:v1.39.0-focal@sha256:bc65d2d0d55fe9b6c5942269380e2a98b7  283.2s
 => => resolve mcr.microsoft.com/playwright:v1.39.0-focal@sha256:bc65d2d0d55fe9b6c5942269380e2a98b798ed542334a9f19a37883  0.0s
 => => sha256:44066a9decc090fe77ff8bef974ccfb26aa7ab55c4e0b0f243f19ca23cc97829 97.59MB / 97.59MB                         19.9s
 => => sha256:bc65d2d0d55fe9b6c5942269380e2a98b798ed542334a9f19a37883573108c58 743B / 743B                                0.0s
 => => sha256:969891e4936b290b9e2050864d6a6b20aad900ffaffbd711e61c88127ee3a974 1.17kB / 1.17kB                            0.0s
 => => sha256:255521f677d5037956b1fff9e33dabb566c76a74d866dbe3d1bdbc62cc166e66 4.02kB / 4.02kB                            0.0s
 => => sha256:7007490126efaae58924972668256aaeb4858e6c4537eb4257e1978719b958c7 28.58MB / 28.58MB                          1.0s
 => => sha256:39db6f40f499336eae2891bd2677bde1e9739497f399378f734ee0343e8385c6 1.80MB / 1.80MB                            1.1s
 => => sha256:52a2e805b52c0271eb25f9220d736a02c59b0b19c52c2f6388bf9aeb288001bd 579.13MB / 579.13MB                      127.1s
 => => extracting sha256:7007490126efaae58924972668256aaeb4858e6c4537eb4257e1978719b958c7                                 1.8s
 => => extracting sha256:44066a9decc090fe77ff8bef974ccfb26aa7ab55c4e0b0f243f19ca23cc97829                                 9.6s
 => => extracting sha256:39db6f40f499336eae2891bd2677bde1e9739497f399378f734ee0343e8385c6                                 0.0s
 => => extracting sha256:52a2e805b52c0271eb25f9220d736a02c59b0b19c52c2f6388bf9aeb288001bd                               118.5s
 => [playwright internal] load build context                                                                              0.1s
 => => transferring context: 2.64kB                                                                                       0.0s
 => [playwright stage-1 2/6] WORKDIR /app                                                                                 0.2s
 => [playwright stage-1 3/6] COPY package.json /app/                                                                      0.1s
 => [playwright stage-1 4/6] COPY playwright.config.js /app/                                                              0.1s
 => [playwright stage-1 5/6] RUN apt-get update && apt-get -y install libnss3 libatk-bridge2.0-0 libdrm-dev libxkbcommo  29.0s
 => [playwright stage-1 6/6] RUN npm install                                                                              8.2s
 => [playwright] exporting to image                                                                                       0.3s
 => => exporting layers                                                                                                   0.3s
 => => writing image sha256:db12cbeefb746507ea2d66a2a20ee41ae6449e8b3e86a4c4b970206a49dc7f20                              0.0s
 => => naming to docker.io/library/deployment-playwright                                                                  0.0s

> e2e@1.0.0 test
> npx playwright test


Running 74 tests using 1 worker
```

2024-01-22 07:58 UTC, kencho51 approved these changes
Hi @pli888

**praise:** I can execute `% docker-compose run --rm playwright npm run test` now.

Besides the 3 failing a11y tests (non blocking):
```
 3 failed
    [chromium] › accessibility.spec.js:61:7 › Page / › should not have any color contrast issues ───
    [firefox] › accessibility.spec.js:61:7 › Page / › should not have any color contrast issues ────
    [webkit] › accessibility.spec.js:61:7 › Page / › should not have any color contrast issues ─────
  71 passed (43.4s)
```
 the code changes LGTM, so happy to approve this PR.

2024-01-22 09:05 UTC, merged