fix 2138: avoid deleting type when deleting a dataset type
gigascience/gigadb-website pull request #2147
Opened 2024-12-23 10:43 UTC by alli83

# Pull request for issue: #2138

avoid deleting type when deleting a dataset type

## How to test?

Describe how the new functionalities can be tested by PR reviewers

## How have functionalities been implemented?

Go to 'dataset'
uncheck a dataset type
Scroll down to save
you should see the dataset type but unchecked

## Any issues with implementation?

## Any changes to automated tests?

## Any changes to documentation?

## Any technical debt repayment?

## Any improvements to CI/CD pipeline?

2025-01-13 06:22 UTC, kencho51 commented on tests/acceptance/AdminDatasetForm.feature
> +  @test
**suggestion:** If the scenario is ready, in our convention, it should be `@ok`.

2025-01-13 07:23 UTC, kencho51 commented on tests/acceptance/AdminDatasetForm.feature
> +    Then I should see "Workflow"
**issue:** I think this scenario does not catch quite right, as stated in #2138, first, each dataset is by default to have at least one dataset type checked, if someone is trying to uncheck the only checked type, it will throw error `Fail to update your types`, like the above scenario, the update action actually has not triggered yet.

**suggestion:** For example the scenarios can be:

```
 Scenario: Type is not removed when uncheck a dataset type
    Given I am on "/adminDataset/update/id/8"
    And I should see "Workflow"
    And I should see "Genomic"
    When I check "Dataset_Workflow" checkbox
    And I press the button "Save"
    And I am on "/adminDataset/update/id/8"
    And I should see "Dataset_Workflow" checkbox is checked
    And I should see "Dataset_Genomic" checkbox is checked
    Then I uncheck "Dataset_Genomic" checkbox
    And I press the button "Save"
    And I am on "/adminDataset/update/id/8"
    And I should see "Genomic"
```

**issue:** Second, when someone unchecked a type from one dataset and saved, the type of the other dataset containing the same type should not be removed.
**suggestion:** For example the scenarios can be:

```
Scenario: Type of another dataset is not removed when uncheck a dataset type
    Given I am on "/adminDataset/update/id/8"
    And I should see "Workflow"
    And I am on "/adminDataset/update/id/200"
    And I should see "Workflow"
    When I am on "/adminDataset/update/id/8"
    And I check "Dataset_Workflow" checkbox
    And I press the button "Save"
    And I am on "/adminDataset/update/id/8"
    Then I uncheck "Dataset_Genomic" checkbox
    And I press the button "Save"
    And I am on "/adminDataset/update/id/200"
    And I should see "Genomic"
```

2025-01-13 08:59 UTC, kencho51 commented on protected/models/Dataset.php
> +                $command->delete('dataset_type', 'dataset_id=:dataset_id AND type_id=:type_id ', array(':dataset_id' => $this->id, ':type_id' => $typeId));
**question(non-blocking):** Why you would prefer executing the raw sql to deletes records from the database, instead of deleting the specific record by invoking the ActiveRecord instance delete() method? I think through the delete() method, it interacts with the database through the model's abstraction layer and can trigger model level logic.

2025-01-21 06:50 UTC, pli888 requested changes
**nitpick**: Tiny bit more constructive information on how to test the functionality in this PR would've been useful. Using the current instructions, I get a `Fail to update your types` error message.
**praise**: Changing the dataset type functionality works as expected after I realised that I need to check another dataset type checkbox after unchecking the current dataset type.
**issue**: I think the acceptance test in `AdminDatasetForm.feature` could be improved so that steps a curator would need to do to change dataset type are defined. Maybe use the `I should see :checkbox checkbox is not checked` assertion to ensure regression of this bug does not happen.
**chore**: Rebase with current develop branch code to resolve conflict in changelog.

2025-02-05 04:27 UTC, alli83 commented on tests/acceptance/AdminDatasetForm.feature
> +    Then I should see "Workflow"
I'm not sure I understand your comment. The purpose of the test is simply to show that when a type is unchecked, the type itself is not deleted (which was the case before)

2025-02-05 04:42 UTC, alli83 commented on protected/models/Dataset.php
> +                $command->delete('dataset_type', 'dataset_id=:dataset_id AND type_id=:type_id ', array(':dataset_id' => $this->id, ':type_id' => $typeId));
the purpose here was just to fix the bug. the problem here is that we are not fetching datasetTypes but rather the type so If I call delete on the model, it will delete the type.

2025-02-10 06:28 UTC, kencho51 commented on tests/acceptance/AdminDatasetForm.feature
> +    Then I should see "Workflow"
From what I got from the ticket #2138 is when someone tries to uncheck a dataset type from one dataset, it will be removed not just from that particular dataset, but also from other datasets as well.

So, the above scenarios I suggested are to make sure that a dataset type can be unchecked from one dataset, and other dataset wont be affected.

2025-02-10 06:30 UTC, alli83 commented on tests/acceptance/AdminDatasetForm.feature
> +    Then I should see "Workflow"
the main cause is that the dataset type itself has been removed.

2025-02-10 06:47 UTC, alli83 commented on tests/acceptance/AdminDatasetForm.feature
> +    Then I should see "Workflow"
I just added another test to double-check but the main cause is the disappearance of te type itself

2025-02-18 13:48 UTC, pli888 approved these changes
**praise**: The code in `protected/models/Dataset.php` fixes the bug by deleting the relevant row(s) in `dataset_type` table when checked Dataset Type checkboxes are unchecked.
**praise**: The new acceptance tests are a welcomed improvement for testing dataset type functionality on dataset admin pages. These tests are passing on my local dev environment.

This PR looks good to me now.

2025-02-18 21:41 UTC, rija commented on protected/models/Dataset.php
> +                $command->delete('dataset_type', 'dataset_id=:dataset_id AND type_id=:type_id ', array(':dataset_id' => $this->id, ':type_id' => $typeId));
@alli83, @kencho51,
I think the SQL is fine for this PR given it's high impact bug, but I also share  @kencho51's concern, it should just work with the framework's ActiveRecord implementation, that's what it's for.
I think we are misusing it. I suspect this line is the culprit or part of the problem:
```
119 'datasetTypes' => array(self::MANY_MANY, 'Type', 'dataset_type(dataset_id,type_id)'),
```
but we can fix that in another PR.

2025-02-18 21:44 UTC, alli83 commented on protected/models/Dataset.php
> +                $command->delete('dataset_type', 'dataset_id=:dataset_id AND type_id=:type_id ', array(':dataset_id' => $this->id, ':type_id' => $typeId));
I totally agree that some things need to be rewritten and are not quite right. But as we discussed, the PR should not mix refactoring with bug fixing

2025-02-18 21:58 UTC, rija approved these changes
Hi @alli83,

**praise**: bug fix works in my setup
**praise**: all tests are passing
**praise**: test coverage has been improved
**praise**: code is good enough

Happy to approve

2025-02-20 01:53 UTC, kencho51 approved these changes
Hi @alli83,

LGTM, happy to approve.

2025-02-20 08:15 UTC, merged