Aws security test for production staging/live containers
gigascience/gigadb-website pull request #846
Opened 2021-11-25 08:49 UTC by kencho51

# Pull request for issue: #822

This is a pull request for the following functionalities:

## Task 1: Verify that docker remote control of staging and live web site is taking place using client cert authentication
1. On staging server
```
user@dev-computer: % ssh -i ~/.ssh/<CustomPrivateKey>.pem -o ProxyCommand="ssh -W %h:%p -i ~/.ssh/<CustomPrivateKey>.pem centos@<bastion_public_ip>" centos@ec2-<docker_public_ip>.<region>.compute.amazonaws.com
[centos@ip-10-99-0-188 ~]$ ls
app_data
[centos@ip-10-99-0-188 ~]$ docker ps
CONTAINER ID   IMAGE                                                                                COMMAND                  CREATED       STATUS       PORTS                                                                                            NAMES
732e957720d3   portainer/portainer-ce:latest                                                        "/portainer -H unix:…"   3 hours ago   Up 3 hours   0.0.0.0:8000->8000/tcp, :::8000->8000/tcp, 9443/tcp, 0.0.0.0:9009->9000/tcp, :::9009->9000/tcp   kencho-gigadb-website_portainer_1
4768f62dcc67   registry.gitlab.com/gigascience/forks/kencho-gigadb-website/production_web:staging   "/docker-entrypoint.…"   3 hours ago   Up 3 hours   0.0.0.0:80->80/tcp, :::80->80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp                         kencho-gigadb-website_web_1
54ceb5461f1c   registry.gitlab.com/gigascience/forks/kencho-gigadb-website/production_app:staging   "docker-php-entrypoi…"   3 hours ago   Up 3 hours   9000/tcp                                                                                         kencho-gigadb-website_application_1
[centos@ip-10-99-0-188 ~]$ 

```
2. On live server
```
user@dev-computer: % ssh -i ~/.ssh/<CustomPrivateKey>.pem -o ProxyCommand="ssh -W %h:%p -i ~/.ssh/<CustomPrivateKey>.pem centos@<bastion_public_ip>" centos@ec2-<docker_public_ip>.<region>.compute.amazonaws.com
[centos@ip-10-99-0-20 ~]$ ls
app_data
[centos@ip-10-99-0-20 ~]$ docker ps
CONTAINER ID   IMAGE                                                                             COMMAND                  CREATED         STATUS         PORTS                                                                                            NAMES
f57a25fdd706   portainer/portainer-ce:latest                                                     "/portainer -H unix:…"   3 minutes ago   Up 3 minutes   0.0.0.0:8000->8000/tcp, :::8000->8000/tcp, 9443/tcp, 0.0.0.0:9009->9000/tcp, :::9009->9000/tcp   kencho-gigadb-website_portainer_1
8b47dcf68a21   registry.gitlab.com/gigascience/forks/kencho-gigadb-website/production_web:live   "/docker-entrypoint.…"   5 minutes ago   Up 5 minutes   0.0.0.0:80->80/tcp, :::80->80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp                         kencho-gigadb-website_web_1
a180228306ad   registry.gitlab.com/gigascience/forks/kencho-gigadb-website/production_app:live   "docker-php-entrypoi…"   5 minutes ago   Up 5 minutes   9000/tcp                                                                                         kencho-gigadb-website_application_1
[centos@ip-10-99-0-20 ~]$ 
```
## Task 2: Run ``docker scan`` on the two images (application and web) and create PBI for future implementation of  recommendations
Since `docker scan` is only available with docker desktop, the other way round is to implement `container_scanning` in gitlab CI/CD pipeline, the official doc could be found at [here](https://docs.gitlab.com/ee/user/application_security/container_scanning/index.html#running-the-standalone-container-scanning-tool). And there is a requests for multiple images scanning in [gitlab forum](https://forum.gitlab.com/t/container-scanning-for-multiple-images/27348)  since 2019.
However, the multiple images scanning of gitlab container scanning tool is [still not fully developed](https://gitlab.com/groups/gitlab-org/-/epics/3139) and [here](https://gitlab.com/gitlab-org/gitlab/-/issues/208758), it could scan all the images, but if images found to have the  same vulnerability, the pipeline security tab would only show one from either of the images, here is the [deep investigation of this problem](https://gitlab.com/gitlab-org/gitlab/-/issues/6946#note_308554624).
To be short, for example, the following vulnerabilities found in both [registry.gitlab.com/gigascience/forks/kencho-gigadb-website/production_web:live](https://gitlab.com/gigascience/forks/kencho-gigadb-website/-/jobs/1813999598) and [registry.gitlab.com/gigascience/forks/kencho-gigadb-website/production_web:staging](https://gitlab.com/gigascience/forks/kencho-gigadb-website/-/jobs/1813999594)
|   STATUS   |      CVE SEVERITY       | PACKAGE NAME | PACKAGE VERSION |                            CVE DESCRIPTION   |           
| ---------- | ---------- | ---------- | ---------- | ---------- |
| Unapproved | Critical CVE-2021-22945 |     curl     |    7.78.0-r0    | When sending data to an MQTT server, libcurl <= 7.73.0 and 7.78.0 could in some circumstances erroneously keep a pointer to an already freed memory area and both use that again in a subsequent call to send data and also free it *again*.  |
| Unapproved | Critical CVE-2021-22945 |   libcurl    |    7.78.0-r0    | When sending data to an MQTT server, libcurl <= 7.73.0 and 7.78.0 could in some circumstances erroneously keep a pointer to an already freed memory area and both use that again in a subsequent call to send data and also free it *again*. |

But, only `registry.gitlab.com/gigascience/forks/kencho-gigadb-website/production_web:staging`'s vulnerabilities could be found in [security tab](https://gitlab.com/gigascience/forks/kencho-gigadb-website/-/pipelines/415210904/?reportType=CONTAINER_SCANNING). It is because each `container_scanning` section would produce one ``gl-container-scanning-report.json`` report, So when it comes time to merge the two separate reports which both contain same vulnerability,  a race condition occurs, and whichever identifier is encountered first will win, and the subsequent occurrence of the vulnerability will be skipped.

This is the [video walkthrough](https://www.youtube.com/watch?v=iiYrvEPT5Fo) created by gitlab on this reported issue. 

## Reported vulnerabilities have been put into PBI
1. https://github.com/gigascience/gigadb-website/issues/844
2. https://github.com/gigascience/gigadb-website/issues/845

## reference
1. https://gitlab.com/gitlab-org/security-products/analyzers/klar/-/blob/efa8e63368df8f2a64c9b395ac913e40ce3f52a2/docs/process-flow.md

2021-11-26 07:58 UTC, pli888 commented
```
user@dev-computer: % ssh -i ~/.ssh/<CustomPrivateKey>.pem -o ProxyCommand="ssh -W %h:%p -i ~/.ssh/<CustomPrivateKey>.pem centos@<bastion_public_ip>" centos@ec2-<docker_public_ip>.<region>.compute.amazonaws.com
[centos@ip-10-99-0-188 ~]$ docker ps
CONTAINER ID   IMAGE                                                                                COMMAND                  CREATED       STATUS       PORTS                                                                                            NAMES
732e957720d3   portainer/portainer-ce:latest                                                        "/portainer -H unix:…"   3 hours ago   Up 3 hours   0.0.0.0:8000->8000/tcp, :::8000->8000/tcp, 9443/tcp, 0.0.0.0:9009->9000/tcp, :::9009->9000/tcp   kencho-gigadb-website_portainer_1
4768f62dcc67   registry.gitlab.com/gigascience/forks/kencho-gigadb-website/production_web:staging   "/docker-entrypoint.…"   3 hours ago   Up 3 hours   0.0.0.0:80->80/tcp, :::80->80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp                         kencho-gigadb-website_web_1
54ceb5461f1c   registry.gitlab.com/gigascience/forks/kencho-gigadb-website/production_app:staging   "docker-php-entrypoi…"   3 hours ago   Up 3 hours   9000/tcp                                                                                         kencho-gigadb-website_application_1
[centos@ip-10-99-0-188 ~]$ 
```

@kencho51 It looks like this is a check to show that SSH into the dockerhost is done via the bastion server and the running docker containers are then listed? To verify if docker remote control is happening, do we not have to check that the Docker daemon on Dockerhost is using TLS to ensure your identity with certificates, etc?

2021-11-29 05:02 UTC, kencho51 commented
> @kencho51 It looks like this is a check to show that SSH into the dockerhost is done via the bastion server and the running docker containers are then listed? To verify if docker remote control is happening, do we not have to check that the Docker daemon on Dockerhost is using TLS to ensure your identity with certificates, etc?

Hi @pli888 By supplying the `docker cmd` at the end of ssh cmd, without physically log into bastion server, the containers on dockerhost server could be controlled as shown in [here](https://github.com/gigascience/gigadb-website/pull/846#task1)

2021-11-30 08:56 UTC, pli888 approved these changes
After confirming I can connect to dockerhost over TLS, I approve this PR. Regarding container scanning for vulnerabilities, we manually keep an eye on any issues between between staging and live deployments.

2021-12-01 18:02 UTC, rija requested changes
Hi @kencho51,

 All tests pass locally and pipeline builds and deploy to staging and live without problems.

Here are some recommendations.

(1) The job extension/inheritance in ``ops/pipelines/gigadb-conformance-security-jobs.yml`` can be reorganised so that the ancestor scan the privy scanner (so we know when there are vulnerability in the scanning tool itself, so we can update) and have all the jobs scanning our images extending from it. That also enables point (2) below.

```
container_scanning:
  stage: conformance and security
  variables:
    CS_SEVERITY_THRESHOLD: critical
    DOCKER_IMAGE: registry.gitlab.com/security-products/container-scanning:4

container_scanning_1:
  extends: container_scanning
  variables:
    DOCKER_IMAGE: registry.gitlab.com/$CI_PROJECT_PATH/production_web:staging

container_scanning_2:
  extends: container_scanning
  variables:
    DOCKER_IMAGE: registry.gitlab.com/$CI_PROJECT_PATH/production_app:staging

container_scanning_3:
  extends: container_scanning
  variables:
    DOCKER_IMAGE: registry.gitlab.com/$CI_PROJECT_PATH/production_web:live

container_scanning_4:
  extends: container_scanning
  variables:
    DOCKER_IMAGE: registry.gitlab.com/$CI_PROJECT_PATH/production_app:live
```

(2) The number suffix ``_#`` added to the jobs name is not a good idea, as we don't know without looking at the details or job configuration which image they relate to.
It's better using something more explicit like ``-app_staging``, ``-web_live`` as suffix.

(3) Don't forget to re-enable the test stage when you're done with final testing of your pipeline changes

2021-12-02 18:11 UTC, rija commented
Hi @kencho51,

Thanks for implementing the changes. They look good.


However, I've found more issues.

(1) The PHP SAST analyser job has a runtime error
(2) There is a mistake in the instructions for provisioning bastion with terraform
(3) Regarding the change to the documentation, it's not quite correct to say "three certificates" at line 594 of ``docs/SETUP_CI_CD_PIPELINE.md``


Suggestions for fixing them:

(1) You can see this problem on your own pipeline actually. Moving the "Conformance and security" stage before the "Test" stage at the top of ``.gitlab-ci.yml`` config file should fix this. That order makes more sense actually as running test is quite costly, so no need to waste resources if conformance is not satisfactory. It doesn't explain the root cause of the issue, but it gets us going for now.

(2) This was actually fixed by @pli888 in PR #848 which I've just merged to ``develop``. So if you synchronise your branch with the main branch, you will have the fix.

(3) Docker daemon installation install both server and client certificates as you need both for authentication purpose (TLS encryption only need  a server certificate), and it's the client certificate that need to be downloaded, so line 594 should says something like "the three files constituting the client certificate" instead.

2021-12-06 15:26 UTC, rija approved these changes
Thanks @kencho51 for the changes. Looks great and I'm happy to approve this PR.

2021-12-06 18:27 UTC, merged