Change typo and style
gigascience/gigadb-website pull request #883
Opened 2021-12-07 10:07 UTC by kencho51

# Pull request for issue: #873 #874 

This is a pull request for the following functionalities:

<Insert description of the proposed new functionalities and how they can be tested>

## Changes to the view template files
1. Fixed the style  <del><em>GigaDB</em></del> GigaDB User policies`.
2. Fixed the typo in `Hosting Statement`. 

## Changes to the style
1. Removed the `<em></em>` from GigaDB User Policies heading.

## Changes to the tests
1. To test that `ll` has been changed to `All`.

2021-12-08 10:59 UTC, rija requested changes
Hi @kencho51,

fix looks ok

however:

* It is not necessary to write a test for change to the static text content (remember what a test suite is for: preserving and increasing the quality of the code, preventing regressions and act as a safety net to the developer when they work on the code). Eventually that text and the fixing of the typo will be handled with a CMS
* The change to styling of a tab title is navigational element, so it's part of the user interface, so it's front-end code, so it's code, so it needs a test

2021-12-10 18:29 UTC, rija approved these changes
Thanks @kencho51, 
tests are all passing locally and on CI and the fixes work on my staging deployment.
Happy to approve this PR

2021-12-13 04:46 UTC, pli888 commented on features/site-overall.feature
> +  All front end views display properly
If we want to be consistent with other feature descriptions then this needs correcting to: `I want to see all front end views displayed properly`

2021-12-13 04:48 UTC, pli888 commented on features/site-overall.feature
> +  @ok @issue-883
I don't think we need the `@issue-883` tag. It's not a tag that I would expect to use in the future to execute a set of acceptance tests.

2021-12-13 04:48 UTC, pli888 commented on features/site-overall.feature
> +      And I should not see "<em>GigaDB</em> User Policies"
Can you check the whitespace formatting? It seems odd compared to other features.

2021-12-13 04:49 UTC, pli888 approved these changes
Code looks good to me - just the cosmetic changes I suggested.

2021-12-17 09:24 UTC, rija requested changes
Hi @kencho51,

it slipped my attention when I looked at this PR last time,

would you mind correct the user story to follow the conventions we use in product backlogs and to be more specific?

In particular,  there is no such user as "gigadb user". Something like this would be better:

>As a website user
>I want to see useful and consistent navigational controls in the website's static pages area
>So that I can easily navigate the legal and help documentations

2021-12-17 09:49 UTC, kencho51 commented
Hi @rija ,
> 
> In particular, there is no such user as "gigadb user". Something like this would be better:
> 
> > As a website user
> > I want to see useful and consistent navigational controls in the website's static pages area
> > So that I can easily navigate the legal and help documentations

I would like to keep this line `So that I can experience a good performance of gigadb website` as this feature is intended to hold the tests for the overall view of the website, like the guideline pages, term of use page, etc.

2021-12-17 14:02 UTC, rija commented
> Hi @rija ,
> 
> > In particular, there is no such user as "gigadb user". Something like this would be better:
> > > As a website user
> > > I want to see useful and consistent navigational controls in the website's static pages area
> > > So that I can easily navigate the legal and help documentations
> 
> I would like to keep this line `So that I can experience a good performance of gigadb website` as this feature is intended to hold the tests for the overall view of the website, like the guideline pages, term of use page, etc.

@kencho51,

The element you are listing are called static content. "Overall" means "Including everything; comprehensive." which is not what these issues are about.
The word "performances" has no place in here, as these are not performances test, we are not assessing how these pages are performing against a baseline.

Acutally, you should probably change the feature's file name to something like ``static-content-navigation.feature``

2021-12-20 04:48 UTC, kencho51 commented
Hi @rija 
> 
> The element you are listing are called static content. "Overall" means "Including everything; comprehensive." which is not what this issue is about since dynamic content is not in scope of this issue. The word "performance" has no place in here, as these are not performance tests, we are not assessing how these pages are performing against a baseline on some measurable criteria.
> 
> Acutally, you should also change the feature's file name to something like `static-content-navigation.feature`

After rebasing to the latest develop code, the acceptence test has been using codeception infrastructure and a new file `StaticContentNavigation.feature` has been created.
And the user story is updated too.

2021-12-21 13:26 UTC, rija approved these changes

2021-12-21 13:28 UTC, rija commented
Thanks @kencho51, all good now!

2021-12-21 13:30 UTC, merged